//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TutorsDataAccess
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tbl_students
    {
        public int ID { get; set; }
        [Display(Name = "Email address")]
        [Required(ErrorMessage = "The email address is required")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        public string StdEmail { get; set; }
         [Required(ErrorMessage = "Please enter First Name", AllowEmptyStrings = false)]
        public string StdFName { get; set; }
         [Required(ErrorMessage = "Please enter Last Name", AllowEmptyStrings = false)]
        public string StdLName { get; set; }
          [Required(ErrorMessage = "Please select Gender", AllowEmptyStrings = false)]
        public string StdGender { get; set; }
          [Required(ErrorMessage = "Please enter Password", AllowEmptyStrings = false)]
          [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
          [StringLength(50, MinimumLength = 8, ErrorMessage = "Password must be 8 characters long")]
        public string Password { get; set; }
          [Required(ErrorMessage = "Please enter Password", AllowEmptyStrings = false)]
          [DataType(System.ComponentModel.DataAnnotations.DataType.Password)]
          [Compare("Password", ErrorMessage = "Passwords should match")]
        public string Confirm { get; set; }
    }
}
